[package]
name = "javascript_and_web"
version = "0.1.0"
author = "https://www.steadylearner.com"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.47"

# Use it for production
[profile.release]
debug = false
lto = true
